Repository HackYourFuture-CPH/CINEMANIA, pull requests merged in 2023-05, with the labels that each got.

#41 removed the test button
  packages/client/src/components/Button/Button.component.js
  packages/client/src/containers/LandingPage/LandingPage.Container.js
Labels: LANDING team

#35 feat: added get movie list endpoint with sorting and filter by catego…
  packages/server/api/controllers/movies.controller.js
  packages/server/api/routes/movies.router.js
Labels: LIST team

#36 feat: added movie list context
  packages/client/src/context/movieListContext.js
Labels: LIST team

#14 feat/view-25 - Simple rating component + movies/:id route
  packages/client/src/App.js
  packages/client/src/components/MovieView/MovieView.component.js
  packages/client/src/components/RatingStars/RatingStars.component.js
Labels: VIEW team

#30 FE/ Feat/Create navbar landing page
  packages/client/public/index.html
  packages/client/src/App.css
  packages/client/src/App.js
  packages/client/src/components/Navbar/Navbar.component.js
  packages/client/src/lib/theme.js
Labels: LANDING team

#27 feat/ BE for featured movie section on the landing page
  packages/server/api/controllers/movies.controller.js
  packages/server/api/routes/movies.router.js
  packages/server/seeds/development/8_favorites.js
Labels: LANDING team

#20 add endpoint to retrieve movies with the same category
  packages/client/.env.example
  packages/server/.env.example
  packages/server/api/controllers/movies.controller.js
  packages/server/api/routes/movies.router.js
Labels: VIEW team

#45 feat/FE featured movie connected to backend
  packages/client/src/components/FeaturedMovie/FeaturedMovie.jsx
Labels: LANDING team

#37 add endpoint to retrieve details of a movie by its id
  packages/server/api/controllers/movies.controller.js
  packages/server/api/routes/movies.router.js
Labels: VIEW team

#50 Feat/BE Create favorite movies endpoint: Landing page
  packages/server/api/controllers/favorites.controller.js
  packages/server/api/routes/favorites.router.js
  packages/server/api/routes/index.js
Labels: LANDING team

#61 refactored router provider and created layout
  packages/client/src/App.js
  packages/client/src/containers/Layout/Layout.jsx
Labels: LANDING team

#62 Read movieID from url passe it down
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
  packages/client/src/components/SimilarMoviesCarousel/SimilarMoviesCarousel.jsx
  packages/client/src/components/TopCastDisplay/TopCastDisplay.jsx
  packages/client/src/containers/MovieDetails/MovieDetails.jsx
Labels: VIEW team

#58 FE/Footer is pixel perfect
  packages/client/src/components/Footer/Footer.jsx
Labels: LANDING team

#65 fix/reset css to reduce browser inconsistencies
  packages/client/src/reset.css
Labels: LANDING team

#64 Footer was added to the Layout and fixed style adn position
  packages/client/src/components/Footer/Footer.jsx
  packages/client/src/containers/Layout/Layout.jsx
Labels: LANDING team

#52 Feat/FE Make navbar pixel perfect landing page
  packages/client/src/App.css
  packages/client/src/components/Navbar/Navbar.jsx
Labels: LANDING team

#53 feat/category component
  packages/client/src/components/Categories/Catagories.jsx
  packages/client/src/components/Categories/CategoryButton.jsx
Labels: LIST team

#67 Feat/fe add hover effect on navbar and add a color variable
  packages/client/src/components/Navbar/Navbar.jsx
  packages/client/src/lib/theme.js
Labels: LANDING team

#60 added event handler for selecting favorite movies
  packages/client/src/components/MovieCard/MovieCard.jsx
  packages/client/src/components/MovieCard/useFavorites.js
Labels: LANDING team

#66 Feat/big movie card structure
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
  packages/client/src/components/RatingStars/RatingStars.jsx
  packages/client/src/components/TopCastDisplay/TopCastDisplay.jsx
Labels: VIEW team

#40 Feat/fe create movie component landing page
  packages/client/src/components/MovieCard/MovieCard.jsx
Labels: LANDING team

#47 add endpoint to retrieve movie crew
  packages/server/api/controllers/crew.controller.js
  packages/server/api/routes/crew.router.js
  packages/server/api/routes/index.js
  packages/server/api/routes/movies.router.js
Labels: VIEW team

#57 Feat/fe latest ratings movies grid view
  packages/client/src/components/LatestRatingMovies/LatestRatingMovies.jsx
  packages/client/src/components/MovieCard/MovieCard.jsx
  packages/client/src/containers/LandingPage/LandingPage.jsx
Labels: LANDING team

#68 Feat/list 24 assemble movie list
  packages/client/src/components/Categories/Categories.jsx
  packages/client/src/components/Categories/CategoryButton.jsx
  packages/client/src/components/MovieList/MovieCard.jsx
  packages/client/src/components/MovieList/MovieList.jsx
  packages/client/src/containers/MovieListPage/MovieListPage.jsx
  packages/client/src/context/movieListContext.js
  packages/server/api/controllers/movies.controller.js
Labels: LIST team

#69 fix/removed-again-test-components-fixed-imports
  packages/client/src/App.js
  packages/client/src/containers/LandingPage/LandingPage.jsx
  packages/client/src/index.css
  packages/client/src/index.js
Labels: LANDING team

#73 FE fetch cast list of a movie form the BE
  packages/client/src/components/TopCastDisplay/TopCastDisplay.jsx
Labels: VIEW team

#72 fetch movie details from BE
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
  packages/client/src/components/RatingStars/RatingStars.jsx
  packages/client/src/containers/MovieDetails/MovieDetails.jsx
  packages/server/api/controllers/movies.controller.js
Labels: VIEW team

#59 Feat/BE latest rated movies endpoint landing page
  packages/server/api/controllers/reviews.controller.js
  packages/server/api/routes/index.js
  packages/server/api/routes/reviews.router.js
Labels: LANDING team

#79 fix/navbar-refactor-resize
  packages/client/src/components/Navbar/Navbar.jsx
Labels: LANDING team

#88 optimised Footer with emotion/styled and removed the bg color
  packages/client/src/components/Footer/Footer.jsx
Labels: LANDING team

#85 Feat/firebase connection
  packages/client/package.json
  packages/client/src/App.js
  packages/client/src/components/Auth/AuthForm.jsx
  packages/client/src/containers/Auth/AuthPage.jsx
  packages/client/src/firebase.js
  yarn.lock
Labels: LANDING team

#78 feat/week1-View/showcase-finish the Carousel function
  packages/client/package.json
  packages/client/src/assets/fallBackMovies.json
  packages/client/src/components/RoundCarousel/Carousel.css
  packages/client/src/components/RoundCarousel/RoundCarousel.jsx
  packages/client/src/components/SimilarMoviesCarousel/SimilarMoviesCarousel.jsx
  packages/client/src/components/TopCastDisplay/TopCastDisplay.jsx
  packages/client/src/containers/CarouselWrapper/SimilarMovies.jsx
  packages/client/src/containers/MovieDetails/MovieDetails.jsx
  yarn.lock
Labels: VIEW team

#87 optimised MovieCard with emotion/styled
  packages/client/src/components/MovieCard/MovieCard.jsx
Labels: LANDING team

#86 optimized LatestRatingMovies component - added emotion/styled and bac…
  packages/client/src/components/LatestRatingMovies/LatestRatingMovies.jsx
Labels: LANDING team

#96 added pagination to the movies endpoint
  packages/server/api/controllers/movies.controller.js
Labels: LIST team

#97 feat/ sortby componenet
  packages/client/src/components/Select/CustomSelect.jsx
Labels: LIST team

#89 REF/LIST-TEAM-BE-movies-refactor
  packages/server/api/controllers/movies.controller.js
Labels: LIST team

#84 Fix/ FE Opimizing featured component - Landing Page
  packages/client/src/components/FeaturedMovie/FeaturedMovie.jsx
Labels: LANDING team

#103 style/ movie list page outlook as on designs
  packages/client/src/containers/MovieListPage/MovieListPage.jsx
Labels: LIST team

#101 Feat/FE most popular movies carousel
  packages/client/src/components/EllipseCarousel/EllipseCarousel.jsx
  packages/client/src/containers/CarouselWrapper/MostPopular.jsx
  packages/client/src/containers/LandingPage/LandingPage.jsx
Labels: LANDING team

#106 feat/BE and FE - fetching landscape pictures for featured movies
  packages/client/src/components/FeaturedMovie/FeaturedMovie.jsx
  packages/server/api/controllers/movies.controller.js
Labels: LANDING team

#99 Feat/FE add and remove favorite movie with heart icon
  packages/client/src/components/MovieCard/MovieCard.jsx
  packages/client/src/components/MovieCard/handlerFavorite.js
  packages/client/src/components/MovieCard/useFavorites.js
  packages/server/api/controllers/favorites.controller.js
Labels: LANDING team

#100 Feat/movie detail container styles
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
  packages/client/src/components/MovieReviews/MovieReviews.jsx
  packages/client/src/components/RoundCarousel/RoundCarousel.jsx
  packages/client/src/components/SimilarMoviesCarousel/SimilarMoviesCarousel.jsx
  packages/client/src/components/TopCastDisplay/TopCastDisplay.jsx
  packages/client/src/containers/CarouselWrapper/SimilarMovies.jsx
  packages/client/src/containers/MovieDetails/MovieDetails.jsx
  packages/client/src/containers/MovieDetailsLayout/MovieDetailsLayout.jsx
  packages/client/src/lib/theme.js
Labels: VIEW team

#110 refactored favourites page
  packages/client/src/App.js
  packages/client/src/components/MovieOverview/MovieCard.jsx
  packages/client/src/components/MovieOverview/MovieList.jsx
  packages/client/src/components/MovieOverview/MovieOverview.jsx
  packages/client/src/containers/FavoritesListPage/FavoritesListPage.jsx
  packages/client/src/containers/MovieListPage/MovieListPage.jsx
  packages/client/src/context/movieListContext.js
Labels: LIST team

#111 Feat/BE create most popular movies endpoint
  packages/client/src/components/EllipseCarousel/EllipseCarousel.jsx
  packages/client/src/containers/CarouselWrapper/MostPopular.jsx
  packages/server/api/controllers/views.controller.js
  packages/server/api/routes/index.js
  packages/server/api/routes/views.router.js
Labels: LANDING team

#109 fix/fix background, heart icons position and color, other small changes
  packages/client/src/components/MovieCard/MovieCard.jsx
Labels: LANDING team

#117 Fix/Refactored isFavorite Logic to Preserve Filled Heart Icon for Movies in User's Favorites Table
  packages/client/src/components/MovieCard/MovieCard.jsx
  packages/client/src/components/MovieCard/handlerFavorite.js
Labels: LANDING team

#118 fix/navbar-overflow-width
  packages/client/src/App.css
Labels: LANDING team

#113 Fix/FE adjust most popular movies component according to design 1440px and link to movies details
  packages/client/src/components/EllipseCarousel/EllipseCarousel.jsx
  packages/client/src/containers/CarouselWrapper/MostPopular.jsx
  packages/client/src/containers/LandingPage/LandingPage.jsx
Labels: LANDING team

#124 removed hover from carousel's btn
  packages/client/src/components/EllipseCarousel/EllipseCarousel.jsx
Labels: LANDING team

#112 fix/FE-adjust design for featuredMovies according to 1440px
  packages/client/src/components/FeaturedMovie/FeaturedMovie.jsx
Labels: LANDING team

#120 feat/LIST-45-reverse-default-sort-direction
  packages/client/src/components/Select/CustomSelect.jsx
  packages/client/src/context/movieListContext.js
  packages/server/api/controllers/movies.controller.js
Labels: LIST team

#127 Footer fixed to the bottom
  packages/client/src/App.css
  packages/client/src/components/Footer/Footer.jsx
Labels: LANDING team

#129 fix/404-height
  packages/client/src/containers/PageNotFound/PageNotFound.Container.jsx
Labels: LANDING team

#130 fix/latest rating comp height
  packages/client/src/components/LatestRatingMovies/LatestRatingMovies.jsx
Labels: LANDING team

#128 Fix/fe be heart icon handler duplicate favorite movies
  packages/client/src/components/LatestRatingMovies/LatestRatingMovies.jsx
  packages/client/src/components/MovieCard/MovieCard.jsx
  packages/client/src/components/MovieCard/useFavorites.js
  packages/server/api/controllers/reviews.controller.js
Labels: LANDING team

#133 feat/added a link to redirect to '/movies/movie-details'
  packages/client/src/components/MovieCard/MovieCard.jsx
Labels: LANDING team

#132 Fixed css styles and syntax
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
  packages/client/src/components/RatingStars/RatingStars.jsx
  packages/client/src/components/ReviewsDisplay/ReviewsDisplay.jsx
  packages/client/src/components/RoundCarousel/Carousel.css
  packages/client/src/components/RoundCarousel/RoundCarousel.jsx
  packages/client/src/components/SimilarMoviesCarousel/SimilarMoviesCarousel.jsx
  packages/client/src/components/TopCastDisplay/TopCastDisplay.jsx
  packages/client/src/containers/MovieDetails/MovieDetails.jsx
  packages/client/src/containers/MovieDetailsLayout/MovieDetailsLayout.jsx
Labels: VIEW team

#141 fix/navbar-logo
  packages/client/src/components/Navbar/Navbar.jsx
Labels: LANDING team

#136 feat/FE- user redirect if not logged in when clicked for adding fav
  packages/client/src/components/MovieCard/useFavorites.js
Labels: LANDING team

#135 fix/navbar-width-like-design
  packages/client/src/components/Navbar/Navbar.jsx
Labels: LANDING team

#140 fixed console errors for abort and rating in the movie card
  packages/client/src/components/MovieCard/MovieCard.jsx
  packages/client/src/components/MovieCard/useFavorites.js
Labels: LANDING team

#131 Feat/be get each review by movie id user
  packages/client/src/components/ReviewsDisplay/ReviewsDisplay.jsx
  packages/client/src/components/RoundCarousel/RoundCarousel.jsx
  packages/server/api/controllers/reviews.controller.js
  packages/server/api/routes/index.js
  packages/server/api/routes/reviews.router.js
Labels: VIEW team

#146 Fix/signup signin css fix
  packages/client/src/components/Auth/Signin.jsx
  packages/client/src/components/Auth/Signup.jsx
  packages/client/src/containers/Auth/AuthPage.jsx
Labels: LANDING team

#147 Fix/form validation signup
  packages/client/src/components/Auth/Signin.jsx
  packages/client/src/components/Auth/Signup.jsx
Labels: LANDING team

#152 Feat/fill review form with be data
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
  packages/client/src/components/RatingStars/RatingStars.jsx
  packages/client/src/components/ReviewDialog/ReviewDialog.jsx
  packages/client/src/components/RoundCarousel/RoundCarousel.jsx
  packages/server/api/controllers/reviews.controller.js
Labels: VIEW team

#148 fetch real reviews and make the button for show all the reviews funct…
  packages/client/src/components/ReviewsDisplay/ReviewsDisplay.jsx
  packages/client/src/containers/MovieDetails/MovieDetails.jsx
Labels: VIEW team

#134 Added pagination to the Movie list page
  packages/client/package.json
  packages/client/src/components/Categories/Categories.jsx
  packages/client/src/components/Categories/CategoryButton.jsx
  packages/client/src/components/Loader/Loader.jsx
  packages/client/src/components/MovieOverview/MovieList.jsx
  packages/client/src/components/MovieOverview/MovieOverview.jsx
  packages/client/src/components/SearchBar/SearchBar.jsx
  packages/client/src/components/Select/CustomSelect.jsx
  packages/client/src/context/movieListContext.js
  packages/client/src/hooks/useDebounce.jsx
  packages/client/src/index.js
  packages/server/api/controllers/movies.controller.js
  yarn.lock
Labels: LIST team

#144 Refactor StarsRating
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
Labels: VIEW team

#153 Feat/modal success error signup
  packages/client/src/App.js
  packages/client/src/components/Auth/Signin.jsx
  packages/client/src/components/Auth/Signup.jsx
  packages/client/src/components/Navbar/Navbar.jsx
Labels: LANDING team

#163 Fix/move modal toggle to usercontext
  packages/client/src/components/Auth/Account.jsx
  packages/client/src/components/Auth/Signin.jsx
  packages/client/src/components/Auth/Signup.jsx
  packages/client/src/context/UserContext.js
Labels: LANDING team

#161 no-match-movie-messages-added-movielist-page
  packages/client/src/components/MovieOverview/MovieList.jsx
Labels: LIST team

#160 imported favourite component and its state handlers from MovieCard.jsx. Added relevant exports to MovieCard.jsx
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
  packages/client/src/components/MovieCard/MovieCard.jsx
Labels: VIEW team

#151 Landing page new arrivals 3D carousel
  packages/client/src/components/NewArrivalsCarousel/NewArrivalsCarousel.jsx
  packages/client/src/components/NewArrivalsCarousel/styles.css
  packages/client/src/components/NewArrivalsCarousel/useNewArrivals.js
  packages/client/src/containers/LandingPage/LandingPage.jsx
  packages/server/api/controllers/movies.controller.js
  packages/server/api/routes/movies.router.js
Labels: LANDING team

#156 feat/added a Snackbar component to inform the user that he is not logged in when he clicks "Add to Cart"
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
Labels: LANDING team

#165 feat/unauthenenticated user favourite page message
  packages/client/src/containers/FavoritesListPage/FavoritesListPage.jsx
Labels: LIST team

#159 Feat/fe shopping cart page
  packages/client/src/App.js
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
  packages/client/src/components/Navbar/Navbar.jsx
  packages/client/src/components/OrderReview/HandleOrder.jsx
  packages/client/src/components/OrderReview/OrderReview.jsx
  packages/client/src/components/RoundCarousel/RoundCarousel.jsx
  packages/client/src/context/orderContext.jsx
Labels: LANDING team

#166 footer, featured, carousels in landing page is done pixel perfect and…
  packages/client/src/components/EllipseCarousel/EllipseCarousel.jsx
  packages/client/src/components/FeaturedMovie/FeaturedMovie.jsx
  packages/client/src/components/Footer/Footer.jsx
  packages/client/src/components/LatestRatingMovies/LatestRatingMovies.jsx
  packages/client/src/components/NewArrivalsCarousel/NewArrivalsCarousel.jsx
  packages/client/src/containers/LandingPage/LandingPage.jsx
Labels: LANDING team

#173 feat/BE-add-tokens-to-new-user
  packages/server/api/controllers/users.controller.js
  packages/server/migrations/20230506175917_users_and_tokens.js
Labels: LANDING team

#171 adds try-catch to the fetching of a movie details. In a case of error displays error message in fallback movie's description
  packages/client/src/assets/fallBackMovies.json
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
  packages/client/src/containers/MovieDetails/MovieDetails.jsx
Labels: VIEW team

#155 refactored review form and other componetns to split fetching of user's review from the form displaying it
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
  packages/client/src/components/RatingStars/RatingStars.jsx
  packages/client/src/components/ReviewDialog/ReviewDialog.jsx
  packages/client/src/containers/MovieDetails/MovieDetails.jsx
Labels: VIEW team

#154 show text if the cast list is empty in cast display component
  packages/client/src/components/TopCastDisplay/TopCastDisplay.jsx
Labels: VIEW team

#174 User gets message if no reviews available, more button hides and add b…
  packages/client/src/components/ReviewsDisplay/ReviewsDisplay.jsx
Labels: VIEW team

#164 Feat/FE-BE Replace user id placeholder to actual user id to add and remove favrotite movie
  packages/client/src/components/MovieCard/useFavorites.js
  packages/client/src/context/UserContext.js
  packages/server/api/controllers/favorites.controller.js
  packages/server/api/controllers/users.controller.js
  packages/server/api/routes/favorites.router.js
  packages/server/api/routes/users.router.js
Labels: LANDING team

#170 Feat/realize review form save update delete function
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
  packages/client/src/components/ReviewDialog/ReviewDialog.jsx
  packages/client/src/containers/MovieDetails/MovieDetails.jsx
  packages/server/api/controllers/reviews.controller.js
  packages/server/api/routes/reviews.router.js
Labels: VIEW team

#157 Feat/BE create shopping cart handler endpoints
  packages/server/api/controllers/orderItems.controller.js
  packages/server/api/controllers/orders.controller.js
  packages/server/api/routes/index.js
  packages/server/api/routes/orderItems.router.js
  packages/server/api/routes/orders.router.js
  packages/server/migrations/20230523235629_orders.js
  packages/server/migrations/20230524003554_order_items.js
Labels: LANDING team

#175 Feat/fe create token balance and show avatar section
  packages/client/src/components/Auth/Signup.jsx
  packages/client/src/components/Navbar/Navbar.jsx
  packages/server/api/controllers/tokens.controller.js
  packages/server/api/routes/favorites.router.js
  packages/server/api/routes/index.js
  packages/server/api/routes/tokens.router.js
Labels: LANDING team

#178 Feat/list 50 add or remove favourite movies
  packages/client/src/App.js
  packages/client/src/components/LoginModal/LoginModal.jsx
  packages/client/src/components/MovieOverview/MovieCard.jsx
  packages/client/src/components/MovieOverview/handleFavorites.js
  packages/client/src/components/Navbar/Navbar.jsx
  packages/client/src/components/SnackBar/SnackBarProvider.jsx
  packages/client/src/containers/FavoritesListPage/FavoritesListPage.jsx
  packages/client/src/context/UserContext.js
  packages/client/src/context/movieListContext.js
Labels: LIST team

#176 fixed rating undefined order review page
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
  packages/client/src/components/OrderReview/OrderReview.jsx
Labels: LANDING team

#167 create edit button in the reviews component
  packages/client/src/App.js
  packages/client/src/assets/fallBackMovies.json
  packages/client/src/components/Auth/Account.jsx
  packages/client/src/components/Auth/Signin.jsx
  packages/client/src/components/Auth/Signup.jsx
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
  packages/client/src/components/EllipseCarousel/EllipseCarousel.jsx
  packages/client/src/components/FeaturedMovie/FeaturedMovie.jsx
  packages/client/src/components/Footer/Footer.jsx
  packages/client/src/components/LatestRatingMovies/LatestRatingMovies.jsx
  packages/client/src/components/MovieCard/MovieCard.jsx
  packages/client/src/components/MovieCard/useFavorites.js
  packages/client/src/components/MovieOverview/MovieCard.jsx
  packages/client/src/components/MovieOverview/MovieList.jsx
  packages/client/src/components/Navbar/Navbar.jsx
  packages/client/src/components/RatingStars/RatingStars.jsx
  packages/client/src/components/ReviewDialog/ReviewDialog.jsx
  packages/client/src/components/ReviewsDisplay/HeaderReview.jsx
  packages/client/src/components/ReviewsDisplay/ReviewItem.jsx
  packages/client/src/components/ReviewsDisplay/ReviewsDisplay.jsx
  packages/client/src/components/RoundCarousel/RoundCarousel.jsx
  packages/client/src/components/TopCastDisplay/TopCastDisplay.jsx
  packages/client/src/containers/Auth/AuthPage.jsx
  packages/client/src/containers/LandingPage/LandingPage.jsx
  packages/client/src/containers/MovieDetails/MovieDetails.jsx
  packages/client/src/context/UserContext.js
  packages/client/src/context/movieListContext.js
  packages/server/api/controllers/crew.controller.js
  packages/server/api/controllers/favorites.controller.js
  packages/server/api/controllers/movies.controller.js
  packages/server/api/controllers/reviews.controller.js
  packages/server/api/controllers/users.controller.js
  packages/server/api/routes/crew.router.js
  packages/server/api/routes/favorites.router.js
  packages/server/api/routes/index.js
  packages/server/api/routes/movies.router.js
  packages/server/api/routes/reviews.router.js
  packages/server/api/routes/users.router.js
  packages/server/migrations/20230506175917_users_and_tokens.js
Labels: VIEW team

#185 fixed several bugs
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
  packages/client/src/components/ReviewsDisplay/ReviewsDisplay.jsx
  packages/client/src/components/TopCastDisplay/TopCastDisplay.jsx
  packages/client/src/containers/MovieDetails/MovieDetails.jsx
Labels: VIEW team

#182 Feat/fe reuse snackar and loggin modal
  packages/client/src/components/LoginModal/LoginModal.jsx
  packages/client/src/components/MovieCard/MovieCard.jsx
  packages/client/src/components/MovieCard/useFavorites.js
  packages/client/src/context/UserContext.js
Labels: LANDING team

#186 Fix/make latest rating section responsive
  packages/client/src/components/LatestRatingMovies/LatestRatingMovies.jsx
  packages/client/src/components/MovieCard/MovieCard.jsx
Labels: LANDING team

#189 feat/Add price in shopping cart page and add movie price in movie backend
  packages/client/src/components/OrderReview/OrderReview.jsx
  packages/server/api/controllers/movies.controller.js
Labels: LANDING team

#184 Landing 107 create pop up notification for added cart
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
  packages/client/src/components/OrderReview/AddToCartConfirmation.jsx
  packages/client/src/containers/MovieDetails/MovieDetails.jsx
  packages/client/src/context/orderContext.jsx
  packages/client/src/lib/theme.js
Labels: LANDING team

#158 Created Edit Rating Button, to navigate unauthenticated user to signup…
  packages/client/src/App.js
  packages/client/src/components/BigMovieCard/BigMovieCard.jsx
Labels: VIEW team

#180 flip arrow added for sorting in catagories page
  packages/client/src/components/Select/CustomSelect.jsx
  packages/client/src/context/movieListContext.js
Labels: LIST team

#194 Feat/fe confirmed order page
  packages/client/src/components/ConfirmedOrderPage/ConfirmedOrderPage.jsx
  packages/client/src/components/OrderReview/AddToCartConfirmation.jsx
  packages/client/src/components/OrderReview/OrderReview.jsx
  packages/client/src/components/OrderReview/utils.js
  packages/client/src/containers/OrderPage/OrderPageLayout.jsx
Labels: LANDING team

#195 fix carousel style
  packages/client/src/components/RoundCarousel/RoundCarousel.jsx
Labels: VIEW team
